README.markdown

Add Code Climate badge to repository to encourage others to help improve the code.

Add Code Climate Badge

---

README.markdown

Point to newer documentation for Rack.
Fixes issue #192

Update link to Rack:Auth

---

lib/geminabox.rb
lib/geminabox/server.rb
test/units/geminabox/server_test.rb

https://github.com/geminabox/geminabox/issues/115
https://github.com/geminabox/geminabox/issues/81

Added index update serializeation via lockfile.  Addresses multiple bug report.

---

README.markdown

Your not you're

---

lib/geminabox/disk_cache.rb
lib/geminabox/gem_store.rb
lib/geminabox/proxy/file_handler.rb
lib/geminabox/proxy/hostess.rb
lib/geminabox/server.rb
lib/rubygems/commands/inabox_command.rb
test/test_support/gem_factory.rb
test/test_support/geminabox_test_case.rb
test/units/geminabox/proxy/splicer_test.rb

1. File.exists? => File.exist?
2. Dir.exists? => Dir.exist?

Remove deprecated warings

---

lib/geminabox.rb
lib/geminabox/server.rb
views/index.erb

Also, avoid showing the delete button in case allow_delete is false
By setting allow_upload, allow_delete and allow_replace to false you basically end up with a readonly geminabox

Add the allow_upload flag

---

lib/geminabox/proxy/copier.rb
lib/geminabox/proxy/file_handler.rb
lib/geminabox/proxy/splicer.rb

Fix https://github.com/geminabox/geminabox/issues/249

Fix allow_remote_failure was not working in proxy/file_handler

---

lib/geminabox.rb
lib/geminabox/server.rb

Fix https://github.com/geminabox/geminabox/issues/278

Fix CSRF vulnerability

---

lib/geminabox_client.rb

Fix https://github.com/geminabox/geminabox/issues/271

gem inabox command should get gemname from gemspec rather than directory name

---

README.md
lib/geminabox/http_adapter/http_client_adapter.rb

Fix https://github.com/geminabox/geminabox/issues/274

Make it be configurable HTTPClient options of Geminabox.http_adapter

---

lib/geminabox/server.rb
views/gem.erb
views/index.erb

Fix CVE-2017-16792 - Stored XSS

---

lib/geminabox/server.rb

The location of geminabox changed to https://github.com/geminabox/geminabox

Update link to issue

---

lib/geminabox/hostess.rb

fix Gemianbox typo in hostess.rb

---

test/integration/pushing_gems/auth_test.rb
test/integration/pushing_gems/basic_test.rb
test/integration/pushing_gems/path_test.rb
test/test_support/geminabox_test_case.rb

add tests for fetching gems

---

README.md
lib/geminabox.rb
lib/geminabox/server.rb

This a quick sketch of what I was thinking, no tests yet. Do you think this is reasonable so far?

Adds on_gem_received hook [#258]

---

lib/geminabox/proxy/splicer.rb
lib/geminabox/server.rb
test/units/geminabox/proxy/splicer_test.rb

Gem.gzip/gunzip are deprecated.
fix #319, #321

Change Gem.gzip/gunzip to Gem::Util.gzip/gunzip

---

views/atom.erb
views/gem.erb
views/index.erb

I confirmed that when I uploaded a gem file with the author, name, platform, and description, it became XSS because it was not escaped in each view.
This is a fix in gemirro.
https://github.com/PierreRambaud/gemirro/commit/8acfb9ce9774128d535e2795d583242bb86d6ea8#diff-d3aacd45db679dbc7d7cc26ec48eb3531ef20c73e13d280179f68679b0aa3365

escape xss

---

README.md

Fix typo in Actions badge URL

---

README.md

Closes #379
Follows up https://github.com/geminabox/geminabox/commit/12f7ae7238dc76a40ff0e220923212e4098d48ad
| | Screenshots |
|-|-|
| before | ![before-379](https://user-images.githubusercontent.com/10229505/172089647-a7a10583-e4d4-4420-b579-53a95b268759.png) |
| after | ![after-379](https://user-images.githubusercontent.com/10229505/172089708-b68d7a3d-2dec-4fd4-997f-e355f47e3eeb.png) |

Use SVG format for Gemfury badge

---

.github/workflows/ruby.yml

Bump actions/checkout from 2 to 3

---

.github/workflows/stale.yml

Enable stale action for issues and PRs

---

.github/workflows/ruby.yml
README.md

Update CI for 1.5 branch

---

.github/workflows/ruby.yml

Enable rubocop-rake in RuboCop

---

lib/geminabox/version.rb

Bump to 2.0.0.pre

---

.github/workflows/gem-push.yml

Automate build and ship the gem (to GitHub Packages only at this moment).

Build a pre-version gem and publish to Packages (for testing purpose only)

---

lib/geminabox.rb
lib/geminabox/server.rb
test/integration/pushing_gems/data_dir_errors_test.rb
test/test_helper.rb
test/test_support/gem_factory.rb
test/test_support/geminabox_test_case.rb
test/units/geminabox/disk_cache_test.rb

```
/tmp -> Dir.tmpdir
/dev/null -> File::NULL
```

Get rid of hardcoded paths

---

lib/geminabox/incoming_gem.rb

Reverts part of https://github.com/geminabox/geminabox/commit/b257c83009241f890dc61adce063502710e2ebb8
Code coverage: 78.98% => 79.04%

Remove a code branch for Ruby 1.8 and earlier

---

public/master.js

Fix lints in #361
- Follows up #361

Prettier JavaScript files

---

.github/workflows/prettier.yml

Enable Prettier for JS files on Actions

---

.github/workflows/prettier.yml
public/master.css

Enable Prettier for CSS files on Actions

---

CHANGELOG.md
lib/geminabox/version.rb

Prepare 2.0.0.rc.1

---

lib/geminabox/version.rb

Release 2.0.0

---

lib/geminabox/version.rb

Prepare 2.0.1

---

README.md

Updates #360 and 22714ae6a88f55a381077681409aab0fe3acf611.

Simplify system requirements: Ruby and RubyGems

---

lib/geminabox/version.rb

Prepare 2.1.0

---

README.md

Follows up #428 🙏 
Closes #427

Update system requirements with RubyGems 2.4 or higher

---

.github/workflows/ruby.yml
.rubocop.yml
README.md
geminabox.gemspec

Drop Ruby 2.2 support

---

.rubocop_todo.yml
Gemfile

Enable Bundler/OrderedGems cop

---

Gemfile

Reverts #383 as #449 was addressed in #454.

Relax multipart-post gem used in tests

---

geminabox.gemspec

Update gemspec to date

---

lib/geminabox/version.rb

Prepare 2.1.0.rc.1

---

lib/geminabox/version.rb

Prepare 2.2.0

---

CONTRIBUTING.md

Just for https://github.com/deepsourcelabs/good-first-issue/pull/438
- https://github.com/deepsourcelabs/good-first-issue/pull/438

Add setup guide for developers

---

.github/workflows/ruby.yml
README.md
geminabox.gemspec

Drop support RubyGems 2.4.x

---

.github/workflows/ruby.yml
.gitignore
Gemfile
README.md
test/requests/atom_feed_test.rb
test/requests/is_api_request_test.rb
test/test_helper.rb
test/test_support/gem_factory.rb
test/test_support/geminabox_test_case.rb
test/units/geminabox/server_test.rb

These changes are cherry picked from https://github.com/geminabox/geminabox/pull/435. They have helped me debugging my changes and to improve coverage.
@tnir can you please merge these to master?
I will then rebase https://github.com/geminabox/geminabox/pull/435 on the new master.
I would suggest to create a real merge commit, so each of the changes can be undone easily if we change our minds later on.
It would be a fast forward anyway.

Test setup changes

---

Rakefile

Avoid Kernel.system on irb

---

README.md

Add geminabox logo to README.md

---

lib/geminabox/server.rb

for compatibility with ruby 3.2+ https://github.com/geminabox/geminabox/pull/511

replace deprecated exists? with exist?

---

.github/workflows/prettier.yml

- Follows up #432 and #433
- Blocks #556

chore(deps-dev): use prettier@3.0.0 as JS/CSS linter
