geminabox/geminabox

- test/units/geminabox/rubygems_dependency_test.rb
Current master test runs result in this error:
```
1) Error:
Geminabox::RubyGemDependencyTest#test_get_list:
ArgumentError: Unknown key: "content_type". Valid keys are: "headers", "status", "body", "exception", "should_timeout"
/Users/kerrimiller/.rvm/gems/ruby-1.9.3-p551/gems/webmock-1.21.0/lib/webmock/util/hash_validator.rb:12:in `block in validate_keys'
/Users/kerrimiller/.rvm/gems/ruby-1.9.3-p551/gems/webmock-1.21.0/lib/webmock/util/hash_validator.rb:10:in `each_key'
/Users/kerrimiller/.rvm/gems/ruby-1.9.3-p551/gems/webmock-1.21.0/lib/webmock/util/hash_validator.rb:10:in `validate_keys'
/Users/kerrimiller/.rvm/gems/ruby-1.9.3-p551/gems/webmock-1.21.0/lib/webmock/response.rb:80:in `options='
/Users/kerrimiller/.rvm/gems/ruby-1.9.3-p551/gems/webmock-1.21.0/lib/webmock/response.rb:25:in …
```
> Move content-type into header as required by latest version of webmock

- lib/geminabox/gem_list_merge.rb
- lib/geminabox/http_adapter/http_client_adapter.rb
- lib/geminabox/rubygems_dependency.rb
- test/units/geminabox/gem_list_merge_test.rb
- test/units/geminabox/rubygems_dependency_test.rb
This PR includes 3 improvements for performance. 
`api/v1/dependencies` returns marshal dump. `api/v1/dependencies.json` returns JSON contents. The former is faster. We should use the former.
```
marshal_url: 1.261804 sec
json_url: 2.01807 sec
```
as an example to resolve dependencies for `rake,flexmock,parallel_tests,simplecov,rr,timecop,test-unit,test-unit-rr,oj,pry,pry-nav,fluent-plugin-s3,fluent-plugin-forest,fluent-plugin-record-reformer,msgpack,json,yajl-ruby,cool.io,http_parser.rb,sigdump,tzinfo,tzinfo-data,strptime`. You can see detail with this commit https://github.com/geminabox/geminabox/pull/230/commits/41e06f716159d3849cd3c330326ba873345ffec9
```
BEFORE: 0.20931879 sec
AFTER: 0.047801906 sec
```
to resolve dependencies for …
> Performance improvement

- lib/geminabox.rb
- lib/geminabox/rubygems_dependency.rb
`https://bundler.rubygems.org/` should be configurable as `https://rubygems.org/`
> Add bundler_ruby_gems_url

- lib/geminabox/proxy/copier.rb
- test/units/geminabox/proxy/copier_test.rb
In case of failure accessing a remote server, Geminabox::Proxy::Copier#get_remote will leave an empty file in the disk. The first call will get HTTP 500, second on, will get 200, with this cached (invalid) empty file. This begin/ensure block deletes the file in case of failure, and raises the original exception.
> Fix: ensure nothing is cached in case of failure.

- lib/geminabox/proxy/file_handler.rb
- lib/geminabox/proxy/hostess.rb
- lib/geminabox/proxy/splicer.rb
- lib/geminabox/version.rb
I believe we are hitting the same race condition that was reported in https://github.com/geminabox/geminabox/issues/202
This PR should fix that race condition by creating a temporary file for the latest_specs and then doing an atomic move.
I have been running this for a few weeks and it solved the issues we had, everything seems to work smoothly.
> Atomic writes proxy latest specs

- lib/geminabox/server.rb
I would like to add an option to perform an incremental reindex.
We have multiple servers running and they share an s3 mounted gems directory. The cache that gets generated when creating the index can be a little slow as it appears to need to read all the gems in the gems directory. However, the incremental index appears to only check for new gems and only indexes those.
Because gems might be added from a different server to the s3 bucket, this will allow us to more efficiently reindex the rest of the servers without needing to update the entire gem index.
```
curl localhost:9292/reindex?incremental=true
```
Also, I noticed an error if I performed incremental updates twice in a row when there were no new gemspecs found so I added an early return.
> Add incremental option to reindex route

- lib/geminabox/disk_cache.rb
There is a possibility that the file is removed by another process
after checking File.exist?.
> disk_cache.rb: ignore Errno::ENOENT, and EOFError

- lib/geminabox_client.rb
Fix https://github.com/geminabox/geminabox/issues/235
For example,
.gem/geminabox
```
---
:host: http://user%40:password@localhost:9292
```
should return `user@` username and `password` password.
> gem inabox command should unescape username/password of geminabox url

- geminabox.gemspec
- lib/geminabox.rb
- lib/geminabox/server.rb
- test/units/geminabox/server_test.rb
Otherwise,
* index would be broken.
* geminabox would run out all of CPU cores with CPU usage 100%.
> Concurrent reindex(:force_rebuild) should be serialized

- lib/geminabox/server.rb
Before, `href("http://www.example/")` would return `#`, as the escaped text starts with `http:&#x2F;&#x2F;` instead of `http://`
> Escape HTML with href a bit later

- lib/geminabox.rb
- lib/geminabox/server.rb
and make the number be configurable
> Make Rack::Session::Pool's expire_after be smaller to save memory

- lib/geminabox/server.rb
Gem.gunzip/inflate have been deprecated in favour of Gem::Util.gunzip/inflate 
(https://github.com/rubygems/rubygems/blob/master/lib/rubygems/util.rb)
> Update rubygems call to gunzip/inflate

- lib/geminabox/server.rb
This PR corrects the scenario where the user has allow_delete enabled and wishes to delete from the gem view page.  This behavior was broken with PR #294
> fix delete action not showing up on gem page if enabled

- geminabox.gemspec
This following message has been output.
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from geminabox.gemspec:13.
```
Environment:
* Rubygems: 3.0.3
* Ruby: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
> Fix deprecation warning of Gem::Specification#has_rdoc

- lib/geminabox.rb
- lib/geminabox/gem_list_merge.rb
- lib/geminabox/server.rb
- test/units/geminabox/gem_list_merge_test.rb
Rather than combine all gems from BOTH repositories, only include
upstream gems if a gem with the same name is NOT PRESENT LOCALLY.
This is a breaking behavior change in the interest of shipping Geminabox
in a "secure by default" configuration.
To restore the previous behavior, exposing yourself to this vuln:
* Set env var: `RUBYGEMS_PROXY_MERGE_STRATEGY=combine_local_and_remote_gem_versions`
* Add to config.ru: `Geminabox.rubygems_proxy_merge_strategy = :combine_local_and_remote_gem_versions`
One reason to keep the old behavior is if you use Geminabox to override
a public gem version with your own private gem build. In this case,
recommend using Bundler to pin to a private gem source or releasing a
forked gem with a different version instead. …
> Prevent "dependency confusion" resulting in a malicious upstream gem taking precedence over a local gem

- CHANGELOG.md
- lib/geminabox/version.rb
Prevent "dependency confusion" resulting in a malicious upstream gem taking precedence over a local gem
> Release 1.3.0

- .travis.yml
- Gemfile
- geminabox.gemspec
- test/test_support/geminabox_test_case.rb
`rss` gem is moved to bundled gem since ruby 3.0.0.
c.f. https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
So I added `rss` to runtime dependency
```ruby
require "bundler/inline"
gemfile(true) do
source "https://rubygems.org"
gem "geminabox", "1.2.0"
end
require "geminabox"
```
```
$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin17]
$ ruby geminabox_patch.rb
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bundler 2.2.3
Using faraday-net_http 1.0.1
Using httpclient 2.8.3
Using builder 3.2.4
Using ruby2_keywords 0.0.4
Using multipart-post 2.1.1
Using nesty 1.0.2
Using reentrant_flock 0.1.1
Using rack 2.2.3
Using tilt 2.0.10
Using mustermann 1.1.1
Using rack-protection 2.1.0
Using faraday 1.3.0
Using sinatra …
```
> Fixed. doesn't work on Ruby 3.0

- .travis.yml
- geminabox.gemspec
- lib/geminabox.rb
Basic premise here is that some systems (including the one I'm using) don't allow writes to `/tmp`.  And any standard system should be using the `TMPDIR` env var to identify where you can actually write to tmp, however this still falls back to `/tmp` in the cases where the var simply doesn't exist, which should make it a non-breaking change for current users.
Also for whatever reason on all my systems I can't bundle it unless I add the gem `rss`...I'm using Ruby 3.0.
> Use environmental TMPDIR for lockfile, and add 'rss' as dependency.

- lib/geminabox/server.rb
- test/units/geminabox/server_test.rb
Rendering the error message was causing a RackLint error, because the value of HTTP Headers is always supposed to be a string
Rack::Lint::LintError: a header value must be a String, but the value of 'Retry-After' is a Integer
Now this error case should behave compliant to the rack specification.
> Fix rendering of 503 error when lock is still held

- README.md
- lib/geminabox.rb
Modern indexes are available in rubygems since rubygems 1.2.0. I think we can deprecate using the old method now?
> Deprecate using legacy index

- .github/workflows/ruby.yml
- Add test with Ruby 3.1 (#377)
- Update Ruby 2.3 through 3.0 to the latest revisions on CI
- Update rubygems 3.2.3 to 3.3.15 (latest 3.x) on CI
- Update rubygems 2.7.9 to 2.7.11 (latex 2.7.x) on CI
> Add test with Ruby 3.1

- Gemfile
Closes #382
We will be able to revert this commit once [multipart-post 2.2.0](https://rubygems.org/gems/multipart-post/versions/2.2.0) is yanked from RubyGems.org.
See the discussion in the future:
- https://github.com/socketry/multipart-post/issues/92#issuecomment-1147101121
> Pin multipart-post 2.1.x on Ruby 2.2 on CI

- Gemfile
Unpin capybara-mechanize gem on CI by tentatively pinning capybara to 3.36.0 or earlier as capybara 3.37.0 has a breaking change to us: https://github.com/teamcapybara/capybara/pull/2546
Replaces #389
Follows up https://github.com/geminabox/geminabox/pull/360/commits/6a7a17b0fc1c79cd52a90b5fb36d8241f991d7f5 and #340
> Unpin capybara-mechanize gem on CI

- lib/geminabox/proxy/copier.rb
- test/units/geminabox/proxy/copier_test.rb
The replacement File.exist? has been around since at least 2006.
> remove File.exists? deprecation warning

- test/units/geminabox/proxy/copier_test.rb
I always think something is wrong when I see a backtrace in test output. I suggest to remove it, as it does not seem to be necessary. I'm assuming this is a forgotten debug output.
> removed confusing backtrace from test output

- CHANGELOG.md
Backport #405 for 1.4.x.
Part of #399
> [1.4 port] Migrate Changelog entries for 1.0.0 and later to GitHub

- CHANGELOG.md
> Migrate Changelog entries for 1.0.0 and later to GitHub

- lib/geminabox/proxy/copier.rb
- lib/geminabox/proxy/file_handler.rb
- lib/geminabox/proxy/splicer.rb
- test/units/geminabox/incoming_gem_test.rb
- test/units/geminabox/proxy/splicer_test.rb
It's a bad idea to depend on text mode for a binary content like gems or gzipped files
> Use a binary mode for file manipulations

- .github/workflows/ruby.yml
- geminabox.gemspec
Part of #422
Also adds testing with RubyGems 1.8.25, which are failing at this moment.
> Drop RubyGems 1.8.24 and earlier

- lib/geminabox/hostess.rb
- lib/geminabox/proxy/hostess.rb
these requests shouldn't be transformed by a middleware like deflater. It could compress the file twice and corrupt it. This header prevents that.
> Do not transform compressed files

- lib/geminabox/indexer.rb
- lib/geminabox/server.rb
As support for RubyGems 1.8.24 and earlier was dropped in #423, we can safely remove the patch for these versions.
Reverts most of #80 
Closes #422
> Remove patch for RubyGems 1.8.24 or earlier

- .github/workflows/stale.yml
All stale PRs has been tackled for a week, now we can use shorter period to make mentions to contributors.
Updates #407
> Move to normal for actions/stale only for PRs

- .github/workflows/ruby.yml
- geminabox.gemspec
Set `required_rubygems_version` to `=> 2.4.0` in gemspec. RubyGems 2.4.x is the default gem of Ruby 2.2.x (the oldest supported Ruby version) (see https://stdgems.org/2.2.0/).
As RubyGems 2.4.x, 2.5.0, and 2.5.1 does not support `gem yank --host` (https://github.com/rubygems/rubygems/pull/1361), tests added in this PR are with RubyGems 2.5.2.
Tests using `gem yank` CLI are always failing with RubyGems 2.4.x as follows:
```
$ bundle exec rake
[...]
Finished in 25.657103s, 1.0523 runs/s, 3.7417 assertions/s.
1) Failure:
GemcutterApiYankTest#test_method: can yank example  [/home/runner/work/geminabox/geminabox/test/test_support/geminabox_test_case.rb:76]:
Gemfile in data dir.
27 runs, 96 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1)
``` …
> Drop support RubyGems 2.3.x and earlier

- lib/geminabox/incoming_gem.rb
`Gem::Package.open` was removed in RubyGems 2.0.0 at https://github.com/rubygems/rubygems/commit/090c39bd5e4a28e51d6ef8de9efa58ed597cc91c
- Original code: 7518da10
- Blocked by #428
> Remove IncomingGem code for RubyGems 1.x

- .github/workflows/ruby.yml
- .rubocop.yml
- .rubocop_todo.yml
`Lint/NonAtomicFileOperation` cop (https://github.com/rubocop/rubocop/pull/10696) is disabled at this moment.
Some TODOs were already resolved in #423 and #429 and are removed.
> Update RuboCop from 1.30.1 to 1.31.0

- lib/geminabox/http_adapter/template_faraday_adapter.rb
See https://lostisland.github.io/faraday/middleware/authentication.
> eliminate a faraday 1.x deprecation warning

- geminabox.gemspec
Limits sinatra dependency to 2.x to disallows 3.x by dropping 1.x.
This helps admins to use Rack 2.x. Rack 2.0, 2.1, and 2.2 are still properly maintained as of this summer.
https://discuss.rubyonrails.org/t/cve-2022-30122-denial-of-service-vulnerability-in-rack-multipart-parsing/80729
> Limit sinatra dependency to 2.x by dropping 1.x

- geminabox.gemspec
- lib/geminabox/http_adapter/template_faraday_adapter.rb
This is now allowed by #385.
- Closes #375
- Updates #360 (which was in a stupid way 🙏 )
> Allow admins to use Faraday v2 with Ruby 2.6+

- geminabox.gemspec
- lib/geminabox/http_adapter/template_faraday_adapter.rb
Use Faraday v2 if you use Ruby 2.6 or higher or v1 if you use Ruby 2.5 or earlier.
We dropped Ruby 2.2 support #449 (#454) and so we do not have to allow admins to use Faraday v0. With a removal of Faraday v0 support, a workaround from #385 can be removed.
> Drop Faraday v0 support

- .github/workflows/ruby.yml
Follows up #461
A workaround is also added to address https://github.com/codeclimate/test-reporter/issues/495.
> Send coverage report to CodeClimate

- .github/workflows/stale.yml
All stale issues have been tackled for two weeks, now we can use shorter period to make mentions to contributors.
Updates #407
> Move to normal for actions/stale only for issues

- Rakefile
Ruby 2.3 has `rubygems` gem as the default gem and it is automatically loaded without `require` or `-r` option.
On Ruby 2.5.0 or higher, a user will not see warning any more.
- https://github.com/ruby/ruby/blob/v2_5_0/NEWS#stdlib-compatibility-issues-excluding-feature-bug-fixes-
Closes #465
I do not think we really need this...
> Remove deprecated arguments for rake console

- .github/workflows/ruby.yml
- Closes #510
Adds Ruby 3.2.2 to CI matrix, and also updates ruby 2.7, 3.0, and 3.1 to the latest revision of each.
> chore(ci): add Ruby 3.2 to CI matrix
